[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "LevelImposter"
authors = [{name = "DigiWorm", email = "DigiWorm@gmail.com"}]
dynamic = ["version", "description"]
